CELL_FILE = './patterns/gosper_glider_gun.csv'

ALIVE_CELL_CHARACTER = 'O'
EMPTY_CELL_CHARACTER = ' '

GENERATION_LABEL = 'GENERATION:'
GENERATION_LABEL_POSITION = (1, 3)
GENERATION_VALUE_POSITION = (1, 15)

GENERATIONS_PER_SECOND_LABEL = 'GENERATIONS/SECOND:'
GENERATIONS_PER_SECOND_LABEL_POSITION = (1, 20)
GENERATIONS_PER_SECOND_VALUE_POSITION = (1, 40)

LIVING_CELLS_LABEL = 'LIVING CELLS:'
LIVING_CELLS_LABEL_POSITION = (1, 45)
LIVING_CELLS_VALUE_POSITION = (1, 60)

LOWER_CASE_Q_KEY = 113
UPPER_CASE_Q_KEY = 81
